export const dataInfo = {
  first: {
    name: 'Kostiantyn',
    secondName: 'Bielozorov',
    position: 'Manual and automation QA engineer',
    email: 'k.bielozorov@gmail.com',
    phone: '+38 (098) 794-95-07',
    socials: {
      linkedin: {
        name: 'linkedin.com/in/k-bielozorov',
        url: 'https://www.linkedin.com/in/k-bielozorov/',
      },
      telegram: {
        name: 'kostya_belozyorov',
        url: 'tg://resolve?domain=kostya_belozyorov',
      },
      github: {
        name: 'Kostiantyn Bielozorov',
        url: 'https://github.com/kosbielozorov',
      },
    },
  },
  experience: {
    title: 'Professional experience',
    description:
      'Here are a few of my most recent work. As a QA engineer, I constantly prioritize 100% client satisfaction. I always enjoy working on my projects, so each one is a new adventure for me. While working on each new project, I attempt to learn new things.',
    jobs: [
      {
        id: 'j-01',
        fromYear: '2022',
        fromMonth: 'May',
        toYear: 'Present',
        toMonth: '',
        companyName: 'Systems Online',
        companyCity: 'Kharkiv',
        position: 'Manual and automation QA engineer',
        responsibilities: [
          'Requirements analysis',
          'Creating and updating test strategy, test plan, test cases, bug reports, test summary reports',
          "Testing of company's web systems",
          'API testing',
          'Cross-browser testing',
          'Functional testing, smoke testing, regression testing, usability testing, ad-hoc testing',
          'The methodology of black-box testing and grey-box testing',
          'Communication with back-end and front-end developers, designers, PM, clients',
          'Improvements proposal product',
        ],
        achievements: [
          'Implement automatic static code analysis (SonarQube)',
          "Web application auto tests coverage from 'zero' (Gitlab CI/CD, JavaScript, Playwright, Testomat.io)",
          'Reducing regression testing time from hours to 15 minutes',
          'Finding defects early in development, leading to cheaper and easier fixes',
          "Email notifications of web application auto tests coverage from 'zero' (Gitlab CI/CD, JavaScript, Playwright, Inbucket/MailPit)",
        ],
      },
      {
        id: 'j-02',
        fromYear: '2021',
        fromMonth: 'May',
        toYear: '2022',
        toMonth: 'May',
        companyName: 'DUS-Level',
        companyCity: 'Kyiv',
        position: 'Manual QA engineer / junior automation QA engineer',
        responsibilities: [
          'Requirements analysis',
          'Creating and updating test cases, bug reports',
          "Testing of company's web systems",
          'Cross-browser testing',
          'Functional testing, smoke testing, regression testing, usability testing, ad-hoc testing',
          'Communication with back-end and front-end developers, designers, PM',
        ],
        achievements: [
          "Implement web application auto tests coverage from 'zero' (Gitlab CI/CD, JavaScript, Playwright)",
        ],
      },
      {
        id: 'j-03',
        fromYear: '2020',
        fromMonth: 'May',
        toYear: '2021',
        toMonth: 'May',
        companyName: 'DVZN',
        companyCity: 'Kyiv',
        position: 'Front-end developer',
        responsibilities: [
          'creating a layout for the design provided',
          'integrating page layouts into the development environment',
          'creating functionality and supporting existing UI components',
          'basic SEO and Website loading optimization',
          'Working on different projects',
          'Communication with back-end developers, designers, seo-specialists',
          'Improvements proposal product',
        ],
        achievements: [
          'Implement code style(Prettier) and code quality(ESLint)',
          'speed up website loading and SEO optimization',
        ],
      },
      {
        id: 'j-04',
        fromYear: '2017',
        fromMonth: 'Mar',
        toYear: '2019',
        toMonth: 'Jul',
        companyName: 'AM.UA',
        companyCity: 'Kyiv',
        position: 'HTML / CSS coder',
        responsibilities: [
          'creating a layout for the design provided',
          'develop features and supporting existing UI components',
          'adapting Websites to various screen and device sizes',
          'integrating page layouts into the development environment',
          'basic SEO and Website loading optimization',
          'Communication with back-end developers, designers, seo-specialists',
          'writing simple JavaScript code',
        ],
        achievements: [
          'implement new modern design and multi-language user interface',
        ],
      },
    ],
  },
  about: {
    title: 'About My Self',
    shortDesc:
      'Skilled in creating and running tests for frontend and backend parts of applications.',
    description: {
      partOne:
        'My name is Kostiantyn. A motivated and skilled QA engineer with experience in testing different parts of applications. For the last 3 years, I have been improving my skills and exploring new ideas. I adapt quickly, keep learning, and enjoy solving new challenges.',
      partTwo:
        'This approach has driven me to keep learning different skills, like UI/UX, software testing, front-end and back-end basics, DevOps, optimization, server management, and database design.',
      partThree:
        'When I face a new problem, I research it deeply to understand it and find effective solutions that can help with similar issues in the future. I am always open to new ideas and ready to share my knowledge with others.',
    },
    skills: [
      {
        count: 1,
        title: 'QA docs & reports',
        img: '/images/first.svg',
        array: [
          'Test strategy',
          'Test plan',
          'Test case',
          'Check list',
          'Bug report',
          'Test run report',
          'Test summary report',
        ],
      },
      {
        count: 2,
        title: 'Front-end testing',
        img: '/images/second.svg',
        array: [
          'HTML / CSS3',
          'JavaScript / Typescript',
          'Adaptive layout',
          'Responsible layout',
          'Black / Gray / White box testing',
          'Integration testing',
          'E2E testing',
        ],
      },
      {
        count: 3,
        title: 'Back-end testing',
        img: '/images/third.svg',
        array: [
          'Database testing',
          'REST API testing',
          'API JSON Schemas testing',
          'Mocking test data',
        ],
      },
      {
        count: 4,
        title: 'Automation testing',
        img: '/images/five.svg',
        array: [
          'Javascript / Typescript',
          'Playwright',
          'REST API testing',
          'API json schema validation',
          'e2e smoke & regression testing',
          'Email testing',
          'Performance testing',
        ],
      },
      {
        count: 5,
        title: 'DevOps and VCS',
        img: '/images/fourth.svg',
        array: [
          'Docker / CI / CD',
          'GitLab',
          'GitHub',
          'SonarQube',
          'Testing Management System',
        ],
      },
      {
        count: 6,
        title: 'Soft and Tools',
        img: '/images/sixth.svg',
        array: [
          'Git',
          'Postman',
          'Playwright',
          'Inbacket / MailPit',
          'Jira / Teamwork',
          'Testomat.io',
          'SonarQube',
        ],
      },
    ],
  },
  contactMe: {
    title: 'Contact me',
    description:
      'I am always open to new ideas and ready to share my knowledge with others. If you have any questions or want to discuss a project, feel free to contact me.',
  },
  skills: {
    techSkills: [
      'HTML5',
      'CSS3',
      'JavaScript / TypeScript',
      'Black/Grey White box testing',
      'Performance testing',
      'Security testing',
      'Regression testing',
      'Sanity testing',
      'Test design techniques',
      'Test documentation',
      'SDLC, STLC',
      'SQL (MySQL)',
    ],
    softSkills: [
      'Analytical thinking',
      'Communication',
      'Teamwork player',
      'Quick learner',
      'Result-oriented',
      'Stress resistant',
      'Punctuality',
      'Problem-solving',
      'Agile, Scrum, Kanban',
      'Attention to detail',
      'Perseverance and the pursuit of professional growth',
    ],
    toolsSkills: [
      'Playwright',
      'Postman',
      'Git',
      'Jira/Teamwork',
      'Pixel Perfect',
      'SonarQube',
      'Testomat',
      'Inbacket/MailPit',
      'Figma/Photoshop',
      'Grafana',
      'Confluence',
      'Developer Tools',
    ],
  },
  summary: {
    description:
      'QA engineer with knowledge of software testing, quality assurance methodologies. Strive to learn new technologies and gain new knowledge by solving problems. Worked with manual and automation web testing.',
  },
  educations: [
    {
      certification: 'Manual QA Engineer',
      company: 'ITVDN',
      year: '2021',
      city: 'Kyiv',
    },
    {
      certification: 'HTML / CSS / JavaScript',
      company: 'Mate Academy',
      year: '2019',
      city: 'Kyiv',
    },
    {
      certification: 'Management of organizations | Specialist',
      company: 'Bila Tserkva National Agrarian University',
      year: '2000 - 2005',
      city: 'Bila Tserkva',
    },
  ],
  languages: [
    {
      name: 'English',
      level: 'Intermediate',
    },
    {
      name: 'Ukrainian',
      level: 'Native',
    },
  ],
};
